name: project_runway
description: A clean TODO application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  equatable: ^1.1.1
  mockito: ^4.1.1
  dartz: ^0.9.0
  shared_preferences: ^0.5.7
  # to check for internet availability
  data_connection_checker: ^0.3.4
  # firebase database
  cloud_firestore: ^0.13.5
  # Bloc for state management
  flutter_bloc: ^4.0.0
  #Fonts Package
  google_fonts: ^1.0.0
  # page indicator
  smooth_page_indicator: ^0.1.5
  # service locator
  get_it: ^4.0.2
  # provider
  provider: ^4.0.5
  # firebase auth
  firebase_auth: ^0.16.0
  # google auth
  google_sign_in: ^4.4.4
  # unique keys
  uuid: ^2.0.4
  # charts for statistics
  charts_flutter: ^0.9.0
  # notifications
  onesignal_flutter: ^2.4.1
  # lottie for better animations
  lottie: ^0.3.3
  # reporting crashes
  firebase_crashlytics: ^0.1.3+3
  # analytics for tab
  # and route transitions
  firebase_analytics: ^5.0.11
  # caching images
  cached_network_image: ^2.2.0+1
  flutter_local_notifications: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google-logo-png-open-2000.png
    - assets/graph-statistics-solid.json
    - assets/lf30_editor_CH6Lht.json
    - assets/lf30_editor_tLnnBp.json
    - assets/lf30_editor_2qKBQS.json
    - assets/hand_animation_dark.json
    - assets/hand_animation_light.json
    - assets/intro_graph_light.png
    - assets/intro_graph_dark.png
    - assets/intro_pedestal_light.png
    - assets/intro_pedestal_dark.png
    - assets/confetti_animation.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
