name: project_runway
description: A clean and Minimalistic TODO application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.36+11

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2                                   #1
  equatable: ^1.1.1                                         #2
  mockito: ^4.1.1                                           #3
  dartz: ^0.9.0                                             #4
  shared_preferences: ^0.5.7                                #5
  # to check for internet availability
  data_connection_checker: ^0.3.4                           #6
  # firebase database
  cloud_firestore: ^0.13.5                                  #7
  # Bloc for state management
  flutter_bloc: ^4.0.0                                      #8
  #Fonts Package
  google_fonts: ^1.0.0                                      #9
  # page indicator
  smooth_page_indicator: ^0.1.5                             #10
  # service locator
  get_it: ^4.0.2                                            #11
  # provider
  provider: ^4.0.5                                          #12
  # firebase auth
  firebase_auth: ^0.16.0                                    #13
  # google auth
  google_sign_in: ^4.4.4                                    #14
  # unique keys
  uuid: ^2.0.4                                              #15
  # charts for statistics
  charts_flutter: ^0.9.0                                    #16
  # notifications
  onesignal_flutter: ^2.4.1                                 #17
  # lottie for better animations
  lottie: ^0.3.3                                            #18
  # reporting crashes
  firebase_crashlytics: ^0.1.3+3                            #19
  # analytics for tab
  # and route transitions
  firebase_analytics: ^5.0.11                               #20
  # caching images
  cached_network_image: ^2.2.0+1                            #21
  # sending notifications from
  # user's device and scheduling
  flutter_local_notifications: ^1.4.3                       #22
  # share app
  share: ^0.6.4+3                                           #23
  # performance monitoring
  firebase_performance: ^0.3.1+8                            #24
  # user feedback tool
  wiredash: 0.0.1                                           #25
  # application info like version number
  package_info: ^0.4.0+18                                   #26
  # url opening handler
  url_launcher: ^5.4.10                                     #27
  # make text linkable
  linkable: ^1.0.4                                          #28
  # picking images from device
  image_picker: ^0.6.7+1                                    #29
  # uploading files
  flutter_uploader: ^1.2.0                                  #30
  rxdart: ^0.24.1                                           #31
  # staggered grid view
  flutter_staggered_grid_view: ^0.3.0                       #32
  # screenshots of the vision board
  screenshot: ^0.2.0                                        #33
  # save images to gallery
  image_gallery_saver: ^1.2.2                               #34
  # permissions for native layer
  permission_handler: ^5.0.1                                #35
  # text recognition
  firebase_ml_vision: ^0.9.4                                #36



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google-logo-png-open-2000.png
    - assets/lf30_editor_CH6Lht.json
    - assets/lf30_editor_tLnnBp.json
    - assets/hand_animation_dark.json
    - assets/hand_animation_light.json
    - assets/intro_graph.png
    - assets/intro_pedestal.png
    - assets/intro_puzzle.png
    - assets/confetti_animation.json
    - assets/no_new_puzzle_animation.json
    - assets/loading_stats_animation.json
    - assets/account_not_linked_animation.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
